// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

void advertiseRequestCommand(void);
void counterCommand(void);
void dataCommand(void);
void infoCommand(void);
void joinCommand(void);
void joinRangeExtenderCommand(void);
void joinSleepyCommand(void);
void emberResetNetworkState(void);
void pjoinCommand(void);
void halReboot(void);
void setSecurityKeyCommand(void);
void setTxOptionsCommand(void);
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryAction("advertise", advertiseRequestCommand, "", ""),
  emberCommandEntryAction("counter", counterCommand, "u", ""),
  emberCommandEntryAction("data", dataCommand, "", ""),
  emberCommandEntryAction("info", infoCommand, "", ""),
  emberCommandEntryAction("join", joinCommand, "u", ""),
  emberCommandEntryAction("join-extender", joinRangeExtenderCommand, "u", ""),
  emberCommandEntryAction("join-sleepy", joinSleepyCommand, "u", ""),
  emberCommandEntryAction("leave", emberResetNetworkState, "", ""),
  emberCommandEntryAction("pjoin", pjoinCommand, "u", ""),
  emberCommandEntryAction("reset", halReboot, "", ""),
  emberCommandEntryAction("set-key", setSecurityKeyCommand, "b", ""),
  emberCommandEntryAction("set-tx-options", setTxOptionsCommand, "u", ""),
  emberCommandEntryTerminator(),
};
