// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

void advertiseCommand(void);
void counterCommand(void);
void formCommand(void);
void infoCommand(void);
void emberResetNetworkState(void);
void pjoinCommand(void);
void halReboot(void);
void sensorsCommand(void);
void setSecurityKeyCommand(void);
void setTxOptionsCommand(void);
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryAction("advertise", advertiseCommand, "", ""),
  emberCommandEntryAction("counter", counterCommand, "u", ""),
  emberCommandEntryAction("form", formCommand, "u", ""),
  emberCommandEntryAction("info", infoCommand, "", ""),
  emberCommandEntryAction("leave", emberResetNetworkState, "", ""),
  emberCommandEntryAction("pjoin", pjoinCommand, "u", ""),
  emberCommandEntryAction("reset", halReboot, "", ""),
  emberCommandEntryAction("sensors", sensorsCommand, "", ""),
  emberCommandEntryAction("set-key", setSecurityKeyCommand, "b", ""),
  emberCommandEntryAction("set-tx-options", setTxOptionsCommand, "u", ""),
  emberCommandEntryTerminator(),
};
